# Training hyperparameters
LEARNING_RATE = 2.5e-5
BATCH_SIZE = 1
NUM_EPOCHS = 1
WEIGHT_DECAY = 1e-4
# Dataset
NUM_WORKERS = 27
SEED = 44
EXPERIMENT_NAME = "test"
OVERFIT_BATCHES = 1

# Compute related
ACCELERATOR = "gpu"
PRECISION = 16
