# Use an appropriate base image for local validation on Jetson
FROM nvcr.io/nvidia/l4t-pytorch:r35.1.0-pth1.12-py3

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN apt-get update && apt-get install -y \
    python3-pip \
    curl \
    libgl1 \
    libnvinfer-dev \
    libnvinfer-plugin-dev \
    libnvonnxparsers-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Rust and Cargo
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Copy requirements.txt and install Python dependencies
COPY requirements.txt /app/requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
RUN mkdir -p /app/saved_images
RUN pip3 uninstall -y opencv-python opencv-contrib-python openv-python-headless
RUN pip3 install "opencv-python-headless<4.3"
ENV LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1
# Run the application
CMD ["streamlit", "run", "facere_divest_spots_detection.py"]